name:                ArchCEREScript
version:             0.1.0.0
github:              "HolosDev/ArchCEREScript"
license:             BSD3
author:              "YongJoon Joe"
maintainer:          "Holos Works <developer@holos.dev>"
copyright:           "2020 Holos Works / PPUZZL Group"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/HolosDev/ArchCEREScript#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- text
- text-short
- text-show
- text-show-instances
- text-trie
- vector
- megaparsec

default-extensions:
- OverloadedStrings
- TypeInType

library:
  source-dirs: src
  other-modules:
  - Nothing

tests:
  Test-Spec:
    main:                Spec.hs
    source-dirs:
    - test
    - tests/Spec
    default-extensions:
    - TemplateHaskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ArchCEREScript
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
    - containers
  Test-Implementation:
    main:                Implementation.hs
    source-dirs:
    - test
    - tests/Implementation
    default-extensions:
    - TemplateHaskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ArchCEREScript
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
    - containers
